### ISSUE TITLE
this will always true, you have to put actual result into assert

### ISSUE THREAD

**Issue by tallinn-learning** [YaninaAQA/maven-junit5-template-changed#1]
https://github.com/YaninaAQA/maven-junit5-template-changed/blob/00bc4cb3fda3bf8262a2bdf2a2eb9ccc67cc0135/src/test/java/org/example/MathUtilsTest.java#L62

**Comment by YaninaAQA** [comment]
Fixed. https://github.com/YaninaAQA/maven-junit5-template-changed/commit/b018b13385f3713bcee69af12914428ade4d677b
