### ISSUE TITLE
please update checklist according to lesson review

### ISSUE THREAD

**Issue by tallinn-learning** [YaninaAQA/maven-junit5-template-changed#4]

**Comment by YaninaAQA** [comment]
I fixed it. https://github.com/YaninaAQA/maven-junit5-template-changed/blob/master/README.MD

**Comment by tallinn-learning** [comment]
with test data when possible to group them

**Comment by YaninaAQA** [comment]
fixed it https://github.com/YaninaAQA/maven-junit5-template-changed
